name: "Run SQL Script"
inputs:
  server:
    required: true
  dbname:
    required: true
  port:
    required: true
  username:
    required: true
  password:
    required: true
  script:
    required: true

runs:
  using: composite
  steps:
    - name: Build Docker image
      run: docker build -t sql-runner .

    - name: Run SQL script in container
      run: |
        docker run --rm \
          -e SERVER="${{ inputs.server }}" \
          -e DB_NAME="${{ inputs.dbname }}" \
          -e PORT="${{ inputs.port }}" \
          -e USERNAME="${{ inputs.username }}" \
          -e PASSWORD="${{ inputs.password }}" \
          -e SCRIPT_FILE="./${{ inputs.script }}" \
          -e LOG_FILE="./${{ inputs.script }}.log" \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          sql-runner
