name: "Run SQL Script"
inputs:
  server:
    required: true
  dbname:
    required: true
  port:
    required: true
  username:
    required: true
  password:
    required: true
  script:
    required: true
runs:
  using: composite
  steps:
    - name: Creating Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        build-args: |
          "SERVER=${{ inputs.server }}"
          "DB_NAME=${{ inputs.dbname }}"
          "PORT=${{ inputs.port }}"
          "USERNAME=${{ inputs.username }}"
          "PASSWORD=${{ inputs.password }}"
          "SCRIPT_FILE=./${{ inputs.script }}"
          "LOG_FILE=./${{ inputs.script }}.log"
